[package]
name = "loxalot-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "loxalot"
path = "src/main.rs"

[dependencies]
clap = { version = "3.1.6", features = ["derive"] }
env_logger = "0.9.0"
log = "0.4.16"
loxalot-scanning = { path = "../../lib/loxalot-scanning" }
