[package]
name = "loxalot-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "loxalot"
path = "src/main.rs"

[dependencies]
clap = "3.1.6"
env_logger = "0.9.0"
loxalot-scanning = { path = "../../lib/loxalot-scanning" }
